{"name":"Hossain Group Turnover Semantic Model","compatibilityLevel":1600,"model":{"culture":"en-US","defaultPowerBIDataSourceVersion":"powerBI_V3","sourceQueryCulture":"en-US","tables":[{"name":"DashboardKPIs","lineageTag":"bdc8117f-6c32-5632-87b1-eebe168b8da4","columns":[{"name":"PeriodStart","dataType":"dateTime","sourceColumn":"PeriodStart","lineageTag":"7051d080-b9ed-5ff4-b316-29010d54a46c","summarizeBy":"none","formatString":"yyyy-mm-dd"},{"name":"PeriodEnd","dataType":"dateTime","sourceColumn":"PeriodEnd","lineageTag":"6249ca12-4936-5f59-9dd1-3a02fa53965d","summarizeBy":"none","formatString":"yyyy-mm-dd"},{"name":"OpeningHeadcount","dataType":"int64","sourceColumn":"OpeningHeadcount","lineageTag":"b5fca65d-089d-5197-9e93-e7b4b5f50449","summarizeBy":"none","formatString":"0"},{"name":"ClosingHeadcount","dataType":"int64","sourceColumn":"ClosingHeadcount","lineageTag":"2fc5e1e8-a485-5fbe-9818-0a17de7fc52d","summarizeBy":"none","formatString":"0"},{"name":"AverageHeadcount","dataType":"double","sourceColumn":"AverageHeadcount","lineageTag":"7b7a768a-43d3-52ca-9bd9-d623b74c84f5","summarizeBy":"none","formatString":"0.00"},{"name":"TotalHires","dataType":"int64","sourceColumn":"TotalHires","lineageTag":"77a4029a-ed7b-50fe-9970-eab3707b3d07","summarizeBy":"none","formatString":"0"},{"name":"TotalExits","dataType":"int64","sourceColumn":"TotalExits","lineageTag":"e7b725b1-c926-5bab-a05f-e61cf782f329","summarizeBy":"none","formatString":"0"},{"name":"TurnoverRate","dataType":"double","sourceColumn":"TurnoverRate","lineageTag":"cab0c2f9-dacd-529c-a456-7e6ad994304e","summarizeBy":"none","formatString":"0.00%"},{"name":"AnnualizedTurnoverRate","dataType":"double","sourceColumn":"AnnualizedTurnoverRate","lineageTag":"efaba715-e557-5c59-bc2d-54c9f1798b5a","summarizeBy":"none","formatString":"0.00%"},{"name":"ActiveEmployees","dataType":"int64","sourceColumn":"ActiveEmployees","lineageTag":"66b271d0-f44d-5190-8ed3-5db05a356019","summarizeBy":"none","formatString":"0"},{"name":"RiskLevel","dataType":"string","sourceColumn":"RiskLevel","lineageTag":"91cd91ba-087b-5ad2-bd6d-85b2e9cbf4cb","summarizeBy":"none"}],"measures":[{"name":"Active Employees","expression":"MAX('DashboardKPIs'[ActiveEmployees])","lineageTag":"9a974c48-dbbb-5779-8419-0ef6b53443eb","formatString":"0"},{"name":"Total Exits","expression":"MAX('DashboardKPIs'[TotalExits])","lineageTag":"e60dfd55-ab2d-56a4-80b4-d94f78e2c07f","formatString":"0"},{"name":"Total Hires","expression":"MAX('DashboardKPIs'[TotalHires])","lineageTag":"81ad7cbe-cdea-517a-b06d-644b2690a43b","formatString":"0"},{"name":"Period Turnover Rate","expression":"MAX('DashboardKPIs'[TurnoverRate])","lineageTag":"8fe88567-8025-58c2-9310-718437954628","formatString":"0.00%"},{"name":"Annualized Turnover Rate","expression":"MAX('DashboardKPIs'[AnnualizedTurnoverRate])","lineageTag":"45e2d393-e850-5931-8c1d-5e412aebb505","formatString":"0.00%"}],"partitions":[{"name":"DashboardKPIs","mode":"import","source":{"type":"m","expression":["let","    Source = Csv.Document(File.Contents(\"__PROJECT_ROOT__/data/processed/dashboard_kpis.csv\"),[Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),","    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),","    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"PeriodStart\", type date}, {\"PeriodEnd\", type date}, {\"OpeningHeadcount\", Int64.Type}, {\"ClosingHeadcount\", Int64.Type}, {\"AverageHeadcount\", type number}, {\"TotalHires\", Int64.Type}, {\"TotalExits\", Int64.Type}, {\"TurnoverRate\", type number}, {\"AnnualizedTurnoverRate\", type number}, {\"ActiveEmployees\", Int64.Type}, {\"RiskLevel\", type text}})","in","    #\"Changed Type\""]}}]},{"name":"CompanyMonthly","lineageTag":"bbd204b8-4a8b-57f5-a52b-bee64df7dada","columns":[{"name":"MonthStart","dataType":"dateTime","sourceColumn":"MonthStart","lineageTag":"21ea2458-6b7e-53ca-8207-afcdd5afa18c","summarizeBy":"none","formatString":"mmm yyyy"},{"name":"MonthLabel","dataType":"string","sourceColumn":"MonthLabel","lineageTag":"9f9f33ba-5cf7-5b06-a62c-71f935967100","summarizeBy":"none"},{"name":"Year","dataType":"int64","sourceColumn":"Year","lineageTag":"49bdfdcc-d06c-551f-bfc4-442a5338515d","summarizeBy":"none","formatString":"0"},{"name":"OpeningHeadcount","dataType":"int64","sourceColumn":"OpeningHeadcount","lineageTag":"5df6fa44-d56a-5a5c-aa19-c95c03570105","summarizeBy":"none","formatString":"0"},{"name":"Hires","dataType":"int64","sourceColumn":"Hires","lineageTag":"377ffdcb-8008-51a7-8bba-1f103348b0e3","summarizeBy":"none","formatString":"0"},{"name":"Exits","dataType":"int64","sourceColumn":"Exits","lineageTag":"d52cea31-5c9a-5334-a643-5cf78d806138","summarizeBy":"none","formatString":"0"},{"name":"ClosingHeadcount","dataType":"int64","sourceColumn":"ClosingHeadcount","lineageTag":"c4aca5ca-5dc3-5253-af44-46dded267722","summarizeBy":"none","formatString":"0"},{"name":"AverageHeadcount","dataType":"double","sourceColumn":"AverageHeadcount","lineageTag":"1d1bc093-2762-510c-a0bf-f58b4c32667d","summarizeBy":"none","formatString":"0.00"},{"name":"TurnoverRate","dataType":"double","sourceColumn":"TurnoverRate","lineageTag":"6332b2d8-66af-5b5a-af75-15042c20477c","summarizeBy":"none","formatString":"0.00%"},{"name":"AnnualizedTurnoverRate","dataType":"double","sourceColumn":"AnnualizedTurnoverRate","lineageTag":"9f3c500e-9418-55bc-b242-7400947afde7","summarizeBy":"none","formatString":"0.00%"},{"name":"RiskLevel","dataType":"string","sourceColumn":"RiskLevel","lineageTag":"fa7b4270-408c-587a-8983-739f20c5fca5","summarizeBy":"none"}],"measures":[{"name":"Monthly Turnover Rate","expression":"MAX('CompanyMonthly'[TurnoverRate])","lineageTag":"1633e96c-adfe-5558-8ed2-f057ccecc057","formatString":"0.00%"},{"name":"Monthly Exits","expression":"SUM('CompanyMonthly'[Exits])","lineageTag":"d6cbbc53-b110-557e-b5c5-79a091c43635","formatString":"0"},{"name":"Monthly Hires","expression":"SUM('CompanyMonthly'[Hires])","lineageTag":"082e5305-161f-517c-bd21-ed395426d8ea","formatString":"0"}],"partitions":[{"name":"CompanyMonthly","mode":"import","source":{"type":"m","expression":["let","    Source = Csv.Document(File.Contents(\"__PROJECT_ROOT__/data/processed/company_monthly_turnover.csv\"),[Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),","    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),","    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"MonthStart\", type date}, {\"MonthLabel\", type text}, {\"Year\", Int64.Type}, {\"OpeningHeadcount\", Int64.Type}, {\"Hires\", Int64.Type}, {\"Exits\", Int64.Type}, {\"ClosingHeadcount\", Int64.Type}, {\"AverageHeadcount\", type number}, {\"TurnoverRate\", type number}, {\"AnnualizedTurnoverRate\", type number}, {\"RiskLevel\", type text}})","in","    #\"Changed Type\""]}}]},{"name":"DepartmentSummary","lineageTag":"653e0920-7eec-55d1-ad41-e5adc3cc494e","columns":[{"name":"Department","dataType":"string","sourceColumn":"Department","lineageTag":"a29072ac-5a11-56bd-a803-5ae6c57e2f7b","summarizeBy":"none"},{"name":"AverageHeadcount","dataType":"double","sourceColumn":"AverageHeadcount","lineageTag":"b9821a93-0e33-50bd-9d75-a389c8779ca9","summarizeBy":"none","formatString":"0.00"},{"name":"Exits","dataType":"int64","sourceColumn":"Exits","lineageTag":"7cc1b96a-db6d-54e4-bd67-c23a8f5af8d5","summarizeBy":"none","formatString":"0"},{"name":"TurnoverRate","dataType":"double","sourceColumn":"TurnoverRate","lineageTag":"db9cb5d2-9015-5100-9f50-1c726de9e82d","summarizeBy":"none","formatString":"0.00%"},{"name":"AnnualizedTurnoverRate","dataType":"double","sourceColumn":"AnnualizedTurnoverRate","lineageTag":"6ad9e8a4-1107-5724-8106-0096d0ed4b3b","summarizeBy":"none","formatString":"0.00%"},{"name":"RiskLevel","dataType":"string","sourceColumn":"RiskLevel","lineageTag":"f0a832f8-eed8-5f4b-94e6-b8492c77408b","summarizeBy":"none"}],"measures":[{"name":"Department Turnover Rate","expression":"MAX('DepartmentSummary'[TurnoverRate])","lineageTag":"6cfa9771-edbe-5c6c-88c9-460be455fd08","formatString":"0.00%"},{"name":"Department Exits","expression":"SUM('DepartmentSummary'[Exits])","lineageTag":"c8ec4df4-bac9-534f-b248-f1e2ff347e8b","formatString":"0"}],"partitions":[{"name":"DepartmentSummary","mode":"import","source":{"type":"m","expression":["let","    Source = Csv.Document(File.Contents(\"__PROJECT_ROOT__/data/processed/department_turnover_summary.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),","    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),","    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Department\", type text}, {\"AverageHeadcount\", type number}, {\"Exits\", Int64.Type}, {\"TurnoverRate\", type number}, {\"AnnualizedTurnoverRate\", type number}, {\"RiskLevel\", type text}})","in","    #\"Changed Type\""]}}]},{"name":"ExitReasonSummary","lineageTag":"9b9294d8-cfc5-5576-9ba5-d8752a712407","columns":[{"name":"ExitReason","dataType":"string","sourceColumn":"ExitReason","lineageTag":"3e4034ba-1410-5cef-a217-050f1559c4d0","summarizeBy":"none"},{"name":"Exits","dataType":"int64","sourceColumn":"Exits","lineageTag":"89282957-64de-5b3d-b351-b092597d8adb","summarizeBy":"none","formatString":"0"},{"name":"SharePct","dataType":"double","sourceColumn":"SharePct","lineageTag":"4331dbf3-787a-5bc7-8562-f77b6e12dea6","summarizeBy":"none","formatString":"0.00%"}],"measures":[{"name":"Exit Count","expression":"SUM('ExitReasonSummary'[Exits])","lineageTag":"b1624182-0332-58d4-9bd6-7762850a86e5","formatString":"0"}],"partitions":[{"name":"ExitReasonSummary","mode":"import","source":{"type":"m","expression":["let","    Source = Csv.Document(File.Contents(\"__PROJECT_ROOT__/data/processed/exit_reason_summary.csv\"),[Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),","    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),","    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ExitReason\", type text}, {\"Exits\", Int64.Type}, {\"SharePct\", type number}})","in","    #\"Changed Type\""]}}]}],"dataAccessOptions":{"legacyRedirects":true,"returnErrorValuesAsNull":true},"annotations":[{"name":"PBI_QueryOrder","value":"[\"DashboardKPIs\",\"CompanyMonthly\",\"DepartmentSummary\",\"ExitReasonSummary\"]"}]}}
